### ISSUE TITLE
jquery not included correctly

### ISSUE THREAD

**Issue by dylang** [mape/node-scraper#1]
I get an error that jquery wasn't found.

ENOENT, No such file or directory '/usr/local/lib/node/.npm/scraper/0.0.2/node_modules/jsdom/usr/local/lib/node/.npm/scraper/0.0.2/package/deps/jquery-1.4.2.min.js'

**Comment by mape** [comment]
Would you mind pasting the entire log?

The only line in the script that acutally "touches" jQuery is:
    Line 30: __dirname+'/../deps/jquery-1.4.2.min.js'

And I don't see ../ in your error message so I'm thinking perhaps it isn't node-scraper that is failing.

**Comment by mape** [comment]
It seems I'm encountering the same issues myself, looking into it.

**Comment by mape** [comment]
Please let me know if the latest update didn't fix this issue for you.

**Comment by mape** [comment]
Seeing how there is no feedback I'll close this issue.
