### ISSUE TITLE
Getting css background-image

### ISSUE THREAD

**Issue by matylla** [mape/node-scraper#10]
``` javascript
jQuery('*').each(function() {
  if (jQuery(this).css("background-image") !== "none") {
    console.log(jQuery(this).css("background-image"));
  }
});
```

This should return all background images of a fetched website instead of an empty string. Any chance for a quick fix?

**Comment by mape** [comment]
node-scraper stands on the shoulder of https://github.com/tmpvar/jsdom where this issue would be better suited.
